# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

all: False
bootstrap: False
docs: False
exclude_check_commit_message: False
exclude_coverage: True
exclude_deploy_client_to_pypi: False
exclude_deploy_client_to_rubygems: False
exclude_deploy_daily_client_to_pypi: False
exclude_deploy_daily_client_to_rubygems: False
exclude_deploy_to_pypi: False
exclude_docs_test: False
exclude_mariadb_test: False
exclude_test_bindings: False
plugin_camel: PulpContainer
plugin_camel_short: Container
plugin_caps: PULP_CONTAINER
plugin_caps_short: CONTAINER
plugin_dash: pulp-container
plugin_dash_short: container
plugin_name: pulp_container
plugin_snake: pulp_container
plugin_snake_short: container
pypi_username: pulp
test: False
travis: True
verbose: False
black: False
check_commit_message: True
coverage: False
deploy_client_to_pypi: True
deploy_client_to_rubygems: True
deploy_daily_client_to_pypi: True
deploy_daily_client_to_rubygems: True
deploy_to_pypi: True
docs_test: True
pydocstyle: True
test_bindings: True
plugin_app_label: container
travis_notifications: None
